In [7]:
import numpy as np

In [10]:
arr = np.array([1,2,3])   # 1x3
scalar = 5  # 1x1
result = arr + scalar
print(result)

# here 5 is broadcasted to [5,5,5] i.e. 1x3


[6 7 8]


In [12]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])   # shape = (2,3)
arr2 = np.array([10, 20, 30])     # 1x3
result = arr1 + arr2
print(result)

# here [10, 20, 30] is broadcasted to [[10, 20, 30],[10, 20, 30]]

[[11 22 33]
 [14 25 36]]


In [15]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])   # shape = (2,3)
arr4 = np.array([[1], [2]])     # shape = (2,1)
result = arr3 + arr4
print(result)

[[2 3 4]
 [6 7 8]]
